### ISSUE TITLE
Trakt authorisation

### ISSUE THREAD

**Issue by roworit** [Wilson-Magic/Masterani-Redux#5]
Hi, I recently started using Trakt and it seems that I can't authorise Trakt on Masterani, I'm currently using Kodi 18 Beta 3 and I'm on an android TV box. Whenever I click on authorise it just closes the Settings menu without displaying the code needed to authorise it. I tried the same thing with Magicality and it worked so I doubt the issue is on my end, then again I'm pretty new to Kodi so I can be mistaken.

**Comment by ruegnueg** [comment]
I asked the same thing a while ago.
it's not implemented. but as masteranime redux use metahandler for plot and fanart it sometimes scrobles correct to Trakt via the generell Trakt addon on kodi.
