### ISSUE TITLE
Masterani not working 

### ISSUE THREAD

**Issue by Cayz181299** [Wilson-Magic/Masterani-Redux#6]
The addon has removed the whole first fairy tail season for some reason, it has everything else but that?

**Comment by JulGer** [comment]
Playing right now. Everything ok.

**Comment by ruegnueg** [comment]
Works fine. Checke Hide Seen Option?

**Comment by islandtj** [comment]
Did something happen this Sunday evening? I'm getting errors while attempting to bring up "Being Watched" and/or "Popular Today". I can get into the "Anime" section but a search just brings me back to the main screen.
