### ISSUE TITLE
The add on is now pretty much dead

### ISSUE THREAD

**Issue by ghettowboy** [Wilson-Magic/Masterani-Redux#8]
Masterani apparently just added captcha verification.....

**Comment by Mikedagreat90** [comment]
Not working for me as well. Can someone confirm?

**Comment by raphfriend** [comment]
Not working here too...

**Comment by ghettowboy** [comment]
Well yeah, like I said the use of captcha now kills it. I wasn't looking for confirmation, I was informing.

**Comment by raphfriend** [comment]
Give a ERROR?

**Comment by Mikedagreat90** [comment]
Actually it was working last night for me so obviously is not a captcha issue?...🤔

**Comment by ghettowboy** [comment]
They removed the captcha verification for now it seems. When I originally posted about it, you had to verify before video would play just like 9A did.

**Comment by xMunch** [comment]
The captcha only triggers if you hit an episode page more times than an average person would in one day.  It was put in place to stop bots and scrapers.  It shouldn't affect the app unless you're using it on a network that visits the site a lot.
